ci: revert workflows with some zizmor findings
Signed-off-by: Devin Buhl <devin@buhl.casa>

diff --git a/.github/workflows/retry-release.yaml b/.github/workflows/retry-release.yaml
--- a/.github/workflows/retry-release.yaml
+++ b/.github/workflows/retry-release.yaml
@@ -64,13 +64,12 @@ jobs:
       - name: Get Container Registry Version
         id: registry
         env:
-          APP: ${{ matrix.app }}
           GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
         run: |
-          if ! version=$(regctl image inspect ghcr.io/${{ github.repository_owner }}/${APP}:rolling \
+          if ! version=$(regctl image inspect ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:rolling \
               | jq --raw-output '.config.Labels["org.opencontainers.image.version"]' 2>/dev/null) || [[ -z "${version}" ]];
           then
-              echo "Failed to get registry version for ${APP}"
+              echo "Failed to get registry version for ${{ matrix.app }}"
               exit 1
           fi
           echo "version=${version}" >> $GITHUB_OUTPUT
@@ -87,12 +86,11 @@ jobs:
       - if: ${{ steps.find-pull-request.outputs.number != '' }}
         name: Retry Release
         env:
-          APP: ${{ matrix.app }}
           GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
         run: | # zizmor: ignore[template-injection]
           gh workflow run release.yaml \
               --repo ${{ github.repository }} \
-              -f app=${APP} \
+              -f app=${{ matrix.app }} \
               -f release=true
 
           {
@@ -100,5 +98,5 @@ jobs:
               echo
               echo '| Container Name | Actual Version | Expected Version |'
               echo '|----------------|------------------|----------------|'
-              echo '| `${APP}` | `${{ steps.registry.outputs.version }}` | `${{ steps.app-options.outputs.version }}` |'
+              echo '| `${{ matrix.app }}` | `${{ steps.registry.outputs.version }}` | `${{ steps.app-options.outputs.version }}` |'
           } >> $GITHUB_STEP_SUMMARY
